"""cpilot report — generate a provenance report for a given run."""

from __future__ import annotations

import json
from pathlib import Path

import typer

from computepilot.artifacts.provenance import ProvenanceBuilder
from computepilot.cli.ui import console
from computepilot.models.run import Run, RunStatus
from computepilot.runtime.state import StateStore


def _get_run(run_id: str) -> Run | None:
    db_path = Path.home() / ".local" / "share" / "computepilot" / "state.db"
    if not db_path.exists():
        console.print("[red]❌ State database does not exist[/red]")
        return None
    state = StateStore(db_path)
    data = state.get_run(run_id)
    if data is None:
        console.print(f"[red]❌ Run '{run_id}' not found[/red]")
        return None
    return Run(
        id=data["id"],
        workflow_id=data["workflow_id"],
        workflow_name=data.get("workflow_name", ""),
        workflow_sha256=data["workflow_sha256"],
        status=RunStatus(data["status"]),
        executor=data["executor"],
        config=json.loads(data["config_json"]),
        created_at=data["created_at"],
        started_at=data.get("started_at"),
        finished_at=data.get("finished_at"),
    )


def report(
    run_id: str = typer.Argument(..., help="Run ID to report", metavar="RUN_ID"),
) -> None:
    """Generate a provenance report (report.md) for a run."""
    run = _get_run(run_id)
    if run is None:
        raise typer.Exit(1)

    builder = ProvenanceBuilder(run)
    manifest = builder.build_manifest()

    # Determine output directory: use run_dir or current directory
    out_dir = run.run_dir if run.run_dir else Path.cwd()
    out_dir.mkdir(parents=True, exist_ok=True)

    # Write manifest.json
    manifest_path = out_dir / "manifest.json"
    builder.write_manifest(manifest_path)

    # Write report.md
    report_path = out_dir / "report.md"
    lines = [
        f"# Workflow Report: {run.workflow_name}",
        "",
        f"- **Run ID:** {run.id}",
        f"- **Workflow:** {run.workflow_name}",
        f"- **Workflow SHA256:** {run.workflow_sha256}",
        f"- **Status:** {run.status.value}",
        f"- **Executor:** {run.executor}",
        f"- **Created:** {run.created_at}",
        "",
        "## Code Version",
        "",
        f"- **Type:** {manifest['code']['type']}",
    ]
    if manifest["code"].get("commit"):
        lines.append(f"- **Commit:** `{manifest['code']['commit']}`")
    lines.extend(
        [
            "",
            "## Artifacts",
            "",
            "*No artifacts registered.*",
            "",
            "---",
            "",
            "_Generated by ComputePilot computepilot report_",
        ]
    )

    report_path.write_text("\n".join(lines) + "\n")
    console.print(f"[green]✓ Report written to {report_path}[/green]")
    console.print(f"[dim]  Manifest: {manifest_path}[/dim]")
